version: '2'
services:
  dtk_dev:
    image: dalg24/dtk_stack:latest
    volumes:
      - ..:/scratch/source/trilinos/12.8.1/DataTransferKit
    environment:
      - TRILINOS_DIR=/scratch/source/trilinos/12.8.1
    container_name: dtk_dev
    command: tail -f /dev/null
    security_opt:
      - seccomp:unconfined
